name: Dynamic README injection
on:
  push:
    branches:
    - main
  workflow_dispatch:
  schedule:
  - cron: "0 12 * * *"
jobs:
  get-quote:
    runs-on: ubuntu-latest
    steps:
      # checkout updated repo
      - name: Checkout Repo
        uses: actions/checkout@v2

      # configure node in runner
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18

      # clean install npm
      - name: Install Dependencies
        run: npm install

      # Continuous Integration
      - name: Integrate
        run: node .

      # Continuous Deployment
      - name: Add To Repo
        run: |
          # git config pull.rebase false
          # git pull
          git add .
          git config --global user.name "JT2M0L3Y"
          git config --global user.email "jtsmoley@icloud.com"
          git commit -m "[Automated] push new quote"

      # Deploy
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force_with_lease: true
