name: Dynamic README injection
on:
  push:
  # run workflow automatically  
  schedule:
  # this will make it run every day at midnight
  - cron: "0 0 * * *"
  # this will allow the workflow to be run manually from GitHub
  workflow_dispatch:
jobs:
  get-quotes:
    runs-on: ubuntu-latest
    steps:
      # checkout updated repo
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      # configure node in runner
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14.6.0

      - name: Create Node Env
        run: npm init

      # clean install npm
      - name: Install Dependencies
        run: npm ci

      # run script found in package.json
      - name: Compile & Run
        run: npm start

      # pull changes from repo
      - name: Pull Changes
        run: |
          git config pull.rebase false
          git pull

      # add & commit changes
      - name: Commit Changes
        env:
          CI_COMMIT_MESSAGE: CI to push new quote
          CI_COMMIT_AUTHOR: Continuous Integration
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "jtsmoley@icloud.com"
          git add .
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"

      # push changes to repo
      - name: Push Changes
        run: git push
