name: Dynamic README injection
on:
  push:
  workflow_dispatch:
  schedule:
  - cron: "0 12 * * *"
jobs:
  get-quote:
    runs-on: ubuntu-latest
    steps:
      # checkout updated repo
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      # configure node in runner
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # clean install npm
      - name: Install Dependencies
        run: npm ci

      # Continuous Integration
      - name: Compile & Run
        run: node .

      # Continuous Deployment
      - name: Deploy
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -m "push new quote"
          git remote add origin https://${{ secrets.GH_TOKEN }}@github.com/JT2M0L3Y/JT2M0L3Y.git
          git push -u origin master
