name: Dynamic README injection
on:
  push:
  schedule: # run workflow automatically
  # this will make it run every day at midnight
  - cron: "0 0 * * *"
jobs:
  get-quotes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Let the magic happen
        uses: actions/setup-node@v3
        with:
          node-version: 14.6.0

      - run: node .

      - name: Add to git repo
        run: |
          git config pull.rebase false
          git pull
          git add .
          git config --global user.name "JT2M0L3Y"
          git config --global user.email "jtsmoley@icloud.com"
          git commit -m "[Automated] README updated with new quote!"

      - name: Push
        uses: ad-m/github-push-action@master
        env:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
