name: Dynamic README injection
on:
  push:
  workflow_dispatch:
  schedule:
  - cron: "0 12 * * *"
jobs:
  get-quote:
    runs-on: ubuntu-latest
    steps:
      # checkout updated repo
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PAT }}

      # configure node in runner
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # clean install npm
      - name: Install Dependencies
        run: npm ci

      # Continuous Integration
      - name: Integrate
        run: node .

      # Continuous Deployment
      - name: Add, Commit
        # git remote set-url origin https://github.com/JT2M0L3Y/JT2M0L3Y.git
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git commit -am "push new quote"

      # Deploy
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
          branch: ${{ github.ref }}
