name: Dynamic README injection
on:
  push:
    branches:
    - main
  workflow_dispatch:
  schedule:
  - cron: "0 12 * * *"
jobs:
  get-quote:
    runs-on: ubuntu-latest
    steps:
      # checkout updated repo
      - name: Checkout Repo
        uses: actions/checkout@v4

      # configure node in runner
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Continuous Integration
      - name: Integrate
        run: npm run update

      # Continuous Deployment
      - name: Add To Repo
        run: |
          git add .
          git config user.name QuoteInjector
          git config user.email QuoteInjector@github.com
          git commit -m "[Automated] push new quote"

      # Deploy
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
